Completed prep-javascript-variables.
HMerizan/prep-91621-code-solutions pull request #10
Opened 2021-09-28 19:39 UTC by HMerizan

<img width="649" alt="Screen Shot 2021-09-28 at 12 33 17 PM" src="https://user-images.githubusercontent.com/90870500/135154548-8442c0bb-3c9e-4468-87cb-f9ac152d1622.png">

2021-09-29 00:22 UTC, thebearingedge requested changes

2021-09-29 00:22 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
Hi Heather! For each of `2`, `true`, and `null`, you want to leave out the quotes so that the JavaScript engine doesn't think you mean string values.

2021-09-30 19:52 UTC, HMerizan commented
<img width="640" alt="Screen Shot 2021-09-30 at 10 11 17 AM" src="https://user-images.githubusercontent.com/90870500/135521329-26a39b25-2b1b-41bd-bbca-0c8948be3d35.png">

2021-09-30 20:01 UTC, thebearingedge approved these changes

2021-09-30 20:53 UTC, merged